// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Printo.Data.Data;

namespace Printo.Data.Migrations
{
    [DbContext(typeof(PrintoContext))]
    [Migration("20200819174342_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Printo.Data.Data.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("AppartmentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NIP")
                        .HasColumnType("nvarchar(9)")
                        .HasMaxLength(9);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ClientID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 342, DateTimeKind.Local).AddTicks(5550),
                            AddedUserID = 1,
                            City = "Nowy Sącz",
                            CompanyFullName = "Joe Doe Co",
                            Email = "jd@gmail.com",
                            HouseNumber = "218b",
                            IsActive = true,
                            NIP = "123456789",
                            Name = "Joe Doe",
                            Phone = "666666666",
                            PostalCode = "33-300",
                            Street = "Lwowska"
                        },
                        new
                        {
                            ClientID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 344, DateTimeKind.Local).AddTicks(8945),
                            AddedUserID = 1,
                            City = "Nowy Jork",
                            CompanyFullName = "MikeShinoda Co",
                            Email = "mikeshinoda@gmail.com",
                            HouseNumber = "52669",
                            IsActive = true,
                            NIP = "123456789",
                            Name = "MikeShinoda",
                            Phone = "555777333",
                            PostalCode = "52-300",
                            Street = "Wallstreet"
                        },
                        new
                        {
                            ClientID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 344, DateTimeKind.Local).AddTicks(8995),
                            AddedUserID = 1,
                            City = "Nowy Sącz",
                            CompanyFullName = "Vitberg Jacek Sikora",
                            Email = "js@gmail.com",
                            HouseNumber = "3",
                            IsActive = true,
                            NIP = "123456789",
                            Name = "Vitberg",
                            Phone = "666666666",
                            PostalCode = "33-300",
                            Street = "Borelowskiego"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.DeliveryAdress", b =>
                {
                    b.Property<int>("DeliveryAdressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("AppartmentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("DeliveryAdressID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("ClientID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("DeliveryAdresses");

                    b.HasData(
                        new
                        {
                            DeliveryAdressID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 347, DateTimeKind.Local).AddTicks(2938),
                            AddedUserID = 1,
                            AppartmentNumber = "1",
                            City = "Nowy Sącz",
                            ClientID = 1,
                            CompanyName = "Joe Doe Co",
                            ContactName = "Joe Doe",
                            HouseNumber = "54",
                            IsActive = true,
                            Phone = "784 138 949",
                            PostalCode = "33-300",
                            Street = "Lwowska"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.DeliveryType", b =>
                {
                    b.Property<int>("DeliveryTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("DeliveryTypeID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("DeliveryTypes");

                    b.HasData(
                        new
                        {
                            DeliveryTypeID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 347, DateTimeKind.Local).AddTicks(6115),
                            AddedUserID = 1,
                            Description = "Odbiór osobisty przez klienta",
                            IsActive = true,
                            Name = "Odbiór"
                        },
                        new
                        {
                            DeliveryTypeID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 347, DateTimeKind.Local).AddTicks(7041),
                            AddedUserID = 1,
                            Description = "Dostawa do klienta",
                            IsActive = true,
                            Name = "Dostawa"
                        },
                        new
                        {
                            DeliveryTypeID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 347, DateTimeKind.Local).AddTicks(7067),
                            AddedUserID = 1,
                            Description = "Wysyłka kurierska",
                            IsActive = true,
                            Name = "Wysyłka"
                        },
                        new
                        {
                            DeliveryTypeID = 4,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 347, DateTimeKind.Local).AddTicks(7071),
                            AddedUserID = 1,
                            Description = "Wysyłka kurieska z opcją za pobraniem",
                            IsActive = true,
                            Name = "Wysyłka za pobraniem"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.Finishing", b =>
                {
                    b.Property<int>("FinishingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("FinishingID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("Finishings");

                    b.HasData(
                        new
                        {
                            FinishingID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 347, DateTimeKind.Local).AddTicks(9118),
                            AddedUserID = 1,
                            Description = "Brak uszlachetnień druku",
                            IsActive = true,
                            Name = "Brak"
                        },
                        new
                        {
                            FinishingID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 347, DateTimeKind.Local).AddTicks(9963),
                            AddedUserID = 1,
                            Description = "Folia błysk jednostronnie na awersie",
                            IsActive = true,
                            Name = "1/0 Folia BŁYSK"
                        },
                        new
                        {
                            FinishingID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 347, DateTimeKind.Local).AddTicks(9989),
                            AddedUserID = 1,
                            Description = "Folia mat jednostronnie na awersie",
                            IsActive = true,
                            Name = "1/0 Folia MAT"
                        },
                        new
                        {
                            FinishingID = 4,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 347, DateTimeKind.Local).AddTicks(9993),
                            AddedUserID = 1,
                            Description = "Folia soft-touch jednostronnie na awersie",
                            IsActive = true,
                            Name = "1/0 Folia SOFT"
                        },
                        new
                        {
                            FinishingID = 5,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 347, DateTimeKind.Local).AddTicks(9996),
                            AddedUserID = 1,
                            Description = "Folia błysk obustronnie",
                            IsActive = true,
                            Name = "1/1 Folia BŁYSK"
                        },
                        new
                        {
                            FinishingID = 6,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 347, DateTimeKind.Local).AddTicks(9999),
                            AddedUserID = 1,
                            Description = "Folia mat obustronnie",
                            IsActive = true,
                            Name = "1/1 Folia MAT"
                        },
                        new
                        {
                            FinishingID = 7,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(2),
                            AddedUserID = 1,
                            Description = "Folia soft-touch obustronnie",
                            IsActive = true,
                            Name = "1/1 Folia SOFT"
                        },
                        new
                        {
                            FinishingID = 8,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(5),
                            AddedUserID = 1,
                            Description = "Folia mat jednostronnie i lakier wybiórczo błysk na awersie",
                            IsActive = true,
                            Name = "1/0 Folia MAT + UV wybiórczo"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.Format", b =>
                {
                    b.Property<int>("FormatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("FormatID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("Formats");

                    b.HasData(
                        new
                        {
                            FormatID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(2158),
                            AddedUserID = 1,
                            Description = "Wymiary w uwagach do druku",
                            IsActive = true,
                            Name = "Inny"
                        },
                        new
                        {
                            FormatID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(2995),
                            AddedUserID = 1,
                            Description = "440x630mm",
                            IsActive = true,
                            Name = "A2+"
                        },
                        new
                        {
                            FormatID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(3020),
                            AddedUserID = 1,
                            Description = "420x610mm",
                            IsActive = true,
                            Name = "A2"
                        },
                        new
                        {
                            FormatID = 4,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(3024),
                            AddedUserID = 1,
                            Description = "297x420mm",
                            IsActive = true,
                            Name = "A3"
                        },
                        new
                        {
                            FormatID = 5,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(3027),
                            AddedUserID = 1,
                            Description = "210x297mm",
                            IsActive = true,
                            Name = "A4"
                        },
                        new
                        {
                            FormatID = 6,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(3029),
                            AddedUserID = 1,
                            Description = "148x210mm",
                            IsActive = true,
                            Name = "A5"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.Machine", b =>
                {
                    b.Property<int>("MachineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("MachineID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            MachineID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(5073),
                            AddedUserID = 1,
                            Description = "Nie dotyczy",
                            IsActive = true,
                            Name = "N/D"
                        },
                        new
                        {
                            MachineID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(5909),
                            AddedUserID = 1,
                            Description = "Druk offsetowy KBA RAPIDA 75",
                            IsActive = true,
                            Name = "KBA"
                        },
                        new
                        {
                            MachineID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(5952),
                            AddedUserID = 1,
                            Description = "Druk offsetowy RYOBI",
                            IsActive = true,
                            Name = "RYOBI"
                        },
                        new
                        {
                            MachineID = 4,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(5957),
                            AddedUserID = 1,
                            Description = "Druk cyfrowy XEROX D700",
                            IsActive = true,
                            Name = "XEROX"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeliveryAdressID")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinishingID")
                        .HasColumnType("int");

                    b.Property<int>("FormatID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReprint")
                        .HasColumnType("bit");

                    b.Property<int?>("MachineID")
                        .HasColumnType("int");

                    b.Property<string>("NetPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaperTypeID")
                        .HasColumnType("int");

                    b.Property<int>("PaperWeightID")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("PostPressID")
                        .HasColumnType("int");

                    b.Property<int>("PrintColorID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductionStageID")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReprintDateAndInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SheetSizeID")
                        .HasColumnType("int");

                    b.Property<string>("SheetsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SheetsNumberPrinted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.Property<int?>("VatRateID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("ClientID");

                    b.HasIndex("DeliveryAdressID");

                    b.HasIndex("DeliveryTypeID");

                    b.HasIndex("FinishingID");

                    b.HasIndex("FormatID");

                    b.HasIndex("MachineID");

                    b.HasIndex("PaperTypeID");

                    b.HasIndex("PaperWeightID");

                    b.HasIndex("PaymentTypeID");

                    b.HasIndex("PostPressID");

                    b.HasIndex("PrintColorID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ProductionStageID");

                    b.HasIndex("SheetSizeID");

                    b.HasIndex("UpdatedUserID");

                    b.HasIndex("VatRateID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Printo.Data.Data.PaperType", b =>
                {
                    b.Property<int>("PaperTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("PaperTypeID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("PaperTypes");

                    b.HasData(
                        new
                        {
                            PaperTypeID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(7994),
                            AddedUserID = 1,
                            Description = "Szczegóły w uwagach do druku",
                            IsActive = true,
                            Name = "Inny"
                        },
                        new
                        {
                            PaperTypeID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(8829),
                            AddedUserID = 1,
                            Description = "Papier powlekany matowy",
                            IsActive = true,
                            Name = "Kreda mat"
                        },
                        new
                        {
                            PaperTypeID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(8854),
                            AddedUserID = 1,
                            Description = "Papier powlekany błyszczący",
                            IsActive = true,
                            Name = "Kreda błysk"
                        },
                        new
                        {
                            PaperTypeID = 4,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 348, DateTimeKind.Local).AddTicks(8857),
                            AddedUserID = 1,
                            Description = "Papier niepowlekany typu offset",
                            IsActive = true,
                            Name = "Offset"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.PaperWeight", b =>
                {
                    b.Property<int>("PaperWeightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grammature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("PaperWeightID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("PaperWeights");

                    b.HasData(
                        new
                        {
                            PaperWeightID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(905),
                            AddedUserID = 1,
                            Description = "",
                            Grammature = "130g",
                            IsActive = true
                        },
                        new
                        {
                            PaperWeightID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(1753),
                            AddedUserID = 1,
                            Description = "",
                            Grammature = "170g",
                            IsActive = true
                        },
                        new
                        {
                            PaperWeightID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(1775),
                            AddedUserID = 1,
                            Description = "",
                            Grammature = "350g + 170g",
                            IsActive = true
                        },
                        new
                        {
                            PaperWeightID = 4,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(1779),
                            AddedUserID = 1,
                            Description = "",
                            Grammature = "250g + 130g",
                            IsActive = true
                        },
                        new
                        {
                            PaperWeightID = 5,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(1782),
                            AddedUserID = 1,
                            Description = "Szczegóły w opisie druku",
                            Grammature = "Inna",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("PaymentTypeID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            PaymentTypeID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(3806),
                            AddedUserID = 1,
                            Description = "Przelew bankowy termin min. 14 dni",
                            IsActive = true,
                            Name = "Przelew"
                        },
                        new
                        {
                            PaymentTypeID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(4716),
                            AddedUserID = 1,
                            Description = "Gotówka przy odbiorze",
                            IsActive = true,
                            Name = "Gotówka"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.PostPress", b =>
                {
                    b.Property<int>("PostPressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("PostPressID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("PostPresses");

                    b.HasData(
                        new
                        {
                            PostPressID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(6766),
                            AddedUserID = 1,
                            Description = "Brak obróbki introligatorskiej",
                            IsActive = true,
                            Name = "Brak"
                        },
                        new
                        {
                            PostPressID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(7615),
                            AddedUserID = 1,
                            Description = "Docięcie do formatu",
                            IsActive = true,
                            Name = "Docięcie"
                        },
                        new
                        {
                            PostPressID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(7639),
                            AddedUserID = 1,
                            Description = "2 zszywki płaskie",
                            IsActive = true,
                            Name = "Oprawa zeszytowa"
                        },
                        new
                        {
                            PostPressID = 4,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(7643),
                            AddedUserID = 1,
                            Description = "Oprawa miękka klejona",
                            IsActive = true,
                            Name = "Oprawa klejona"
                        },
                        new
                        {
                            PostPressID = 5,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(7646),
                            AddedUserID = 1,
                            Description = "Składanie do formatu",
                            IsActive = true,
                            Name = "Falcowanie"
                        },
                        new
                        {
                            PostPressID = 6,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(7649),
                            AddedUserID = 1,
                            Description = "Szczgóły w opisie do zamówienia",
                            IsActive = true,
                            Name = "Inna obróbka"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.PrintColor", b =>
                {
                    b.Property<int>("PrintColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("PrintColorID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("PrintColors");

                    b.HasData(
                        new
                        {
                            PrintColorID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 349, DateTimeKind.Local).AddTicks(9689),
                            AddedUserID = 1,
                            Description = "CMYK jednostronnie",
                            IsActive = true,
                            Name = "4/0 CMYK"
                        },
                        new
                        {
                            PrintColorID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(515),
                            AddedUserID = 1,
                            Description = "CMYK obustronnie",
                            IsActive = true,
                            Name = "4/4 CMYK"
                        },
                        new
                        {
                            PrintColorID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(539),
                            AddedUserID = 1,
                            Description = "Czarny jednostronnie",
                            IsActive = true,
                            Name = "1/0 blacK"
                        },
                        new
                        {
                            PrintColorID = 4,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(543),
                            AddedUserID = 1,
                            Description = "Czarny obustronnie",
                            IsActive = true,
                            Name = "1/1 blacK"
                        },
                        new
                        {
                            PrintColorID = 5,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(546),
                            AddedUserID = 1,
                            Description = "Okładka: CMYK obustronnie + Środek: czarny obustronnie",
                            IsActive = true,
                            Name = "4/4 CMYK + 1/1 blacK"
                        },
                        new
                        {
                            PrintColorID = 6,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(549),
                            AddedUserID = 1,
                            Description = "Pantone jednostronnie",
                            IsActive = true,
                            Name = "1/0 Pantone"
                        },
                        new
                        {
                            PrintColorID = 7,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(552),
                            AddedUserID = 1,
                            Description = "Szczegóły w uwagach do druku",
                            IsActive = true,
                            Name = "Inny"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(6431),
                            AddedUserID = 1,
                            Description = "Szczegóły w opisie zamówienia",
                            IsActive = true,
                            Name = "Inny"
                        },
                        new
                        {
                            ProductID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(7256),
                            AddedUserID = 1,
                            Description = "Arkusze bez obróbki introligatorskiej",
                            IsActive = true,
                            Name = "Arkusz plano"
                        },
                        new
                        {
                            ProductID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(7279),
                            AddedUserID = 1,
                            Description = "Ulotka standardowa cięta do formatu",
                            IsActive = true,
                            Name = "Ulotka standardowa"
                        },
                        new
                        {
                            ProductID = 4,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(7283),
                            AddedUserID = 1,
                            Description = "Plakat standardowy cięty do formatu",
                            IsActive = true,
                            Name = "Plakat"
                        },
                        new
                        {
                            ProductID = 5,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(7286),
                            AddedUserID = 1,
                            Description = "Szycie zeszytowe standrd lub oczkowe",
                            IsActive = true,
                            Name = "Katalog szyty"
                        },
                        new
                        {
                            ProductID = 6,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(7289),
                            AddedUserID = 1,
                            Description = "Oprawa miękka klejona",
                            IsActive = true,
                            Name = "Katalog klejony"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.ProductionStage", b =>
                {
                    b.Property<int>("ProductionStageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ProductionStageID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("ProductionStages");

                    b.HasData(
                        new
                        {
                            ProductionStageID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(3132),
                            AddedUserID = 1,
                            Description = "Nowe zamówienie przyjęte do realizacji",
                            IsActive = true,
                            Name = "NOWE"
                        },
                        new
                        {
                            ProductionStageID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(4339),
                            AddedUserID = 1,
                            Color = "orange",
                            Description = "Naświetlanie CTP",
                            IsActive = true,
                            Name = "CTP"
                        },
                        new
                        {
                            ProductionStageID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(4371),
                            AddedUserID = 1,
                            Color = "Limegreen",
                            Description = "Etap drukowania",
                            IsActive = true,
                            Name = "START"
                        },
                        new
                        {
                            ProductionStageID = 4,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(4375),
                            AddedUserID = 1,
                            Color = "red",
                            Description = "Produkcja zatrzymana/anulowana",
                            IsActive = true,
                            Name = "STOP"
                        },
                        new
                        {
                            ProductionStageID = 5,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(4378),
                            AddedUserID = 1,
                            Color = "deepskyblue",
                            Description = "Obróbka introligatorska i uszlachetnienia",
                            IsActive = true,
                            Name = "INTRO"
                        },
                        new
                        {
                            ProductionStageID = 6,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(4381),
                            AddedUserID = 1,
                            Color = "black",
                            Description = "Produkcja zakończona - zamówienie gotowe do wydania",
                            IsActive = true,
                            Name = "GOTOWE"
                        },
                        new
                        {
                            ProductionStageID = 7,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(4386),
                            AddedUserID = 1,
                            Description = "Zamówienie zrealizowane",
                            IsActive = true,
                            Name = "KONIEC"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.SheetSize", b =>
                {
                    b.Property<int>("SheetSizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("SheetSizeID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("SheetSizes");

                    b.HasData(
                        new
                        {
                            SheetSizeID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 350, DateTimeKind.Local).AddTicks(9328),
                            AddedUserID = 1,
                            Description = "630x440mm",
                            IsActive = true,
                            Name = "A2+"
                        },
                        new
                        {
                            SheetSizeID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 351, DateTimeKind.Local).AddTicks(155),
                            AddedUserID = 1,
                            Description = "610x430mm",
                            IsActive = true,
                            Name = "A2"
                        },
                        new
                        {
                            SheetSizeID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 351, DateTimeKind.Local).AddTicks(178),
                            AddedUserID = 1,
                            Description = "700x500mm",
                            IsActive = true,
                            Name = "B2"
                        },
                        new
                        {
                            SheetSizeID = 4,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 351, DateTimeKind.Local).AddTicks(182),
                            AddedUserID = 1,
                            Description = "440x315mm",
                            IsActive = true,
                            Name = "A3+"
                        },
                        new
                        {
                            SheetSizeID = 5,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 351, DateTimeKind.Local).AddTicks(185),
                            AddedUserID = 1,
                            Description = "430x305mm",
                            IsActive = true,
                            Name = "A3"
                        },
                        new
                        {
                            SheetSizeID = 6,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 351, DateTimeKind.Local).AddTicks(188),
                            AddedUserID = 1,
                            Description = "Szczegóły w uwagach do druku",
                            IsActive = true,
                            Name = "Inny"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.ToDo", b =>
                {
                    b.Property<int>("ToDoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ToDoID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            ToDoID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 351, DateTimeKind.Local).AddTicks(2825),
                            AddedUserID = 1,
                            Date = new DateTime(2020, 8, 19, 19, 43, 41, 351, DateTimeKind.Local).AddTicks(1877),
                            Description = "Zamówić 2 ryzy papieru",
                            IsActive = true,
                            Name = "Przykładowa notatka"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("UserTypeID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 346, DateTimeKind.Local).AddTicks(2492),
                            IsActive = true,
                            Login = "admin",
                            Name = "Admin",
                            Password = "admin",
                            Surname = "Admin",
                            UserTypeID = 1
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.UserType", b =>
                {
                    b.Property<int>("UserTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserTypeID");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            UserTypeID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 346, DateTimeKind.Local).AddTicks(5351),
                            Description = "Administrator systemu",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            UserTypeID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 346, DateTimeKind.Local).AddTicks(5814),
                            Description = "Pracownik",
                            IsActive = true,
                            Name = "Pracownik"
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.VatRate", b =>
                {
                    b.Property<int>("VatRateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("VatRateID");

                    b.HasIndex("AddedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("VatRates");

                    b.HasData(
                        new
                        {
                            VatRateID = 1,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 346, DateTimeKind.Local).AddTicks(8247),
                            Description = "Standardowa stawka Vat",
                            IsActive = true,
                            Name = "23%",
                            Rate = 23
                        },
                        new
                        {
                            VatRateID = 2,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 346, DateTimeKind.Local).AddTicks(8715),
                            Description = "Stawka Vat przy numerze ISSN",
                            IsActive = true,
                            Name = "8%",
                            Rate = 8
                        },
                        new
                        {
                            VatRateID = 3,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 346, DateTimeKind.Local).AddTicks(8736),
                            Description = "Stawka Vat przy numerze ISBN",
                            IsActive = true,
                            Name = "5%",
                            Rate = 5
                        },
                        new
                        {
                            VatRateID = 5,
                            AddedDate = new DateTime(2020, 8, 19, 19, 43, 41, 346, DateTimeKind.Local).AddTicks(8739),
                            Description = "Nie dotyczy",
                            IsActive = true,
                            Name = "nd",
                            Rate = 0
                        });
                });

            modelBuilder.Entity("Printo.Data.Data.Client", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.DeliveryAdress", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.Client", "Client")
                        .WithMany("DeliveryAdresses")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.DeliveryType", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.Finishing", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.Format", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.Machine", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.Order", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printo.Data.Data.DeliveryAdress", "DeliveryAdress")
                        .WithMany()
                        .HasForeignKey("DeliveryAdressID");

                    b.HasOne("Printo.Data.Data.DeliveryType", "DeliveryType")
                        .WithMany()
                        .HasForeignKey("DeliveryTypeID");

                    b.HasOne("Printo.Data.Data.Finishing", "Finishing")
                        .WithMany()
                        .HasForeignKey("FinishingID");

                    b.HasOne("Printo.Data.Data.Format", "Format")
                        .WithMany()
                        .HasForeignKey("FormatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printo.Data.Data.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineID");

                    b.HasOne("Printo.Data.Data.PaperType", "PaperType")
                        .WithMany()
                        .HasForeignKey("PaperTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printo.Data.Data.PaperWeight", "PaperWeight")
                        .WithMany()
                        .HasForeignKey("PaperWeightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printo.Data.Data.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeID");

                    b.HasOne("Printo.Data.Data.PostPress", "PostPress")
                        .WithMany()
                        .HasForeignKey("PostPressID");

                    b.HasOne("Printo.Data.Data.PrintColor", "PrintColor")
                        .WithMany()
                        .HasForeignKey("PrintColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printo.Data.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printo.Data.Data.ProductionStage", "ProductionStage")
                        .WithMany()
                        .HasForeignKey("ProductionStageID");

                    b.HasOne("Printo.Data.Data.SheetSize", "SheetSize")
                        .WithMany()
                        .HasForeignKey("SheetSizeID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");

                    b.HasOne("Printo.Data.Data.VatRate", "VatRate")
                        .WithMany()
                        .HasForeignKey("VatRateID");
                });

            modelBuilder.Entity("Printo.Data.Data.PaperType", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.PaperWeight", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.PaymentType", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.PostPress", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.PrintColor", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.Product", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.ProductionStage", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.SheetSize", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.ToDo", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });

            modelBuilder.Entity("Printo.Data.Data.User", b =>
                {
                    b.HasOne("Printo.Data.Data.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Printo.Data.Data.VatRate", b =>
                {
                    b.HasOne("Printo.Data.Data.User", "AddedUser")
                        .WithMany()
                        .HasForeignKey("AddedUserID");

                    b.HasOne("Printo.Data.Data.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID");
                });
#pragma warning restore 612, 618
        }
    }
}
